name: Test and deploy snapshot

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.gitignore'
    - 'docs/**'


jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Mark version as SNAPSHOT
      run: sed -i '0,/<version>/{s/\(<version>[^<]*\)\(<\/version>\)/\1-SNAPSHOT\2/}' pom.xml

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Test project
      run: mvn test --file pom.xml

    - name: Build with Maven
      run: mvn package -Dmaven.test.skip

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[{"id": "maven-snapshots", "url": "https://repo.knighthat.me/repository/maven-snapshots/"}]'
        servers: ' [{"id": "knighthat", "username": "${{ secrets.REPO_NAME }}", "password": "${{ secrets.REPO_PASSWD }}"}]'
        output_file: ".m2/settings.xml"

    - name: Deploy to remote repository
      run: mvn deploy --settings .m2/settings.xml -Dmaven.test.skip
