name: Test and deploy

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.gitignore'
    - 'docs/**'


jobs:
  install_ytdl:

    runs-on: ubuntu-latest

    steps:
    - name: Download YTDL
      run: git clone --depth 1 https://github.com/ytdl-org/youtube-dl ytdl

    - name: Make executable
      run: |
        echo "#\!/bin/bash\n\n/usr/bin/python $PWD/ytdl/youtube_dl/__main__.py \$@" > youtube-dl
        
        chmod +x youtube-dl
        
        echo "$(youtube-dl --version)"

    - name: Move executable to PATH
      run: |
        sudo mv youtube-dl /usr/bin/youtube-dl
        
        echo "$(/usr/bin/youtube-dl --version)"


  build:

    runs-on: ubuntu-latest
    needs: install_ytdl

    steps:
    - name: Verify youtube-dl
      run: echo "$(/usr/bin/youtube-dl --version)"

    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - id: extractor
      name: Extract version from pom.xml
      run: |
        echo "groupid=$(grep -oP '<groupId>\K[^<]+' pom.xml | head -n1)" >> $GITHUB_OUTPUT

        echo "artifactid=$(grep -oP '<artifactId>\K[^<]+' pom.xml | head -n1)" >> $GITHUB_OUTPUT

        echo "version=$(grep -oP '<version>\K[^<]+' pom.xml | head -n1)" >> $GITHUB_OUTPUT

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[{"id": "maven-snapshots", "url": "https://repo.knighthat.me/repository/maven-snapshots/"}]'
        servers: ' [{"id": "knighthat", "username": "${{ secrets.REPO_NAME }}", "password": "${{ secrets.REPO_PASSWD }}"}]'
        output_file: ".m2/settings.xml"

    - name: Deploy to remote repository
      run: mvn deploy --settings .m2/settings.xml -Dmaven.test.skip=true
