name: Test and deploy

on:
  push:
  branches: [ "dev" ]


jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      groupId: ${{ steps.extractor.outputs.groupid }}
      artifactId: ${{ steps.extractor.outputs.artifactid }}
      version: ${{ steps.extractor.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - id: extractor
        name: Extract version from pom.xml
        run: |
          echo "groupid=$(grep -oP '<groupId>\K[^<]+' pom.xml | head -n1)" >> $GITHUB_OUTPUT

          echo "artifactid=$(grep -oP '<artifactId>\K[^<]+' pom.xml | head -n1)" >> $GITHUB_OUTPUT

          echo "version=$(grep -oP '<version>\K[^<]+' pom.xml | head -n1)" >> $GITHUB_OUTPUT

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://repo.knighthat.me
        username: ${{ secrets.REPO_NAME }}
        password: ${{ secrets.REPO_PASSWD }}
        format: maven2
        repository: maven-snapshots
        coordinates: groupId=${{ needs.build.outputs.groupId }} artifactId=${{ needs.build.outputs.artifactId }} version=${{ needs.build.outputs.version }}
        assets: extension=jar
        filename: ./target/${{ needs.build.outputs.artifactId }}-${{ needs.build.outputs.version }}.jar
