name: Test and deploy

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.gitignore'
    - 'docs/**'


jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Download YTDL
      uses: actions/checkout@v4
      with:
        repository: ytdl-org/youtube-dl
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ./ytdl
      
    - name: Make executable
      run: |
        sudo ln -s $PWD/ytdl/youtube_dl/__main__.py /usr/bin/youtube-dl

        sudo chmod +x /usr/bin/youtube-dl

    - name: Verify youtube-dl command
      run: echo "$(youtube-dl --version)"

    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Test project
      run: mvn test --file pom.xml

    - name: Build with Maven
      run: mvn package -Dmaven.test.skip

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[{"id": "maven-snapshots", "url": "https://repo.knighthat.me/repository/maven-snapshots/"}]'
        servers: ' [{"id": "knighthat", "username": "${{ secrets.REPO_NAME }}", "password": "${{ secrets.REPO_PASSWD }}"}]'
        output_file: ".m2/settings.xml"

    - name: Deploy to remote repository
      run: mvn deploy --settings .m2/settings.xml -Dmaven.test.skip
